Repository metallang/metal, pull requests merged in 2024-12, with the labels that each got.

#87 deps: Automated nightly version update.
  .github/workflows/clippy.yml
  .github/workflows/rustfmt.yml
  .github/workflows/shear.yml
  .github/workflows/test.yml
Labels: a: deps

#89 deps: Automated nightly version update.
  .github/workflows/clippy.yml
  .github/workflows/rustfmt.yml
  .github/workflows/shear.yml
  .github/workflows/test.yml
Labels: a: deps

#83 refactor!: mir refactor
  crates/metal-codegen-llvm/src/core.rs
  crates/metal-codegen-llvm/src/lib.rs
  crates/metal-codegen-llvm/src/primitives.rs
  crates/metal-codegen-llvm/src/stmt/constant.rs
  crates/metal-codegen-llvm/src/stmt/function_definition.rs
  crates/metal-codegen-llvm/src/ty.rs
  crates/metal-codegen-llvm/src/ty/function_signature.rs
  crates/metal-codegen-llvm/src/ty/struct_.rs
  crates/metal-mir/src/expr/function_call.rs
  crates/metal-mir/src/expr/literals.rs
  crates/metal-mir/src/expr/mod.rs
  crates/metal-mir/src/parcel.rs
  crates/metal-mir/src/stmt/constant.rs
  crates/metal-mir/src/stmt/functiondef.rs
  crates/metal-mir/src/stmt/import.rs
  crates/metal-mir/src/stmt/mod.rs
  crates/metal-mir/src/stmt/return_.rs
  crates/metal-mir/src/struct_.rs
  crates/metal-mir/src/types/array.rs
  crates/metal-mir/src/types/function.rs
  crates/metal-mir/src/types/mod.rs
  crates/metal-mir/src/types/primitives.rs
  crates/metal-mir/src/types/tuple.rs
  crates/metal-mir/src/types/visibility.rs
  mir-tests/test_strings.ron
  mir-tests/test_structs.ron
  mir-tests/test_variables.ron
Labels: a: llvm, a: mir

#96 docs(readme): beautify a bit
  README.md
Labels: a: docs
