Repository metallang/metal, pull requests merged in 2024-10, with the labels that each got.

#6 ci: Limit workflow concurrency, run CI on `pull_request`, remove `merge_group` trigger.
  .github/workflows/audit.yml
  .github/workflows/clippy.yml
  .github/workflows/nightlies.yml
  .github/workflows/rustfmt.yml
  .github/workflows/shear.yml
  .github/workflows/test.yml
Labels: pr: bugfix, a: ci/cd

#5 fix(metal-proc-macros): Split macro implementations into submodules.
  crates/metal-proc-macros/src/lib.rs
  crates/metal-proc-macros/src/spans/attribute.rs
  crates/metal-proc-macros/src/spans/derive.rs
  crates/metal-proc-macros/src/spans/mod.rs
Labels: pr: improvement, a: codeq

#7 fix(metal-proc-macros): Use `proc-macro-error2` for error handling.
  Cargo.toml
  crates/metal-proc-macros/Cargo.toml
  crates/metal-proc-macros/src/lib.rs
  crates/metal-proc-macros/src/spans/attribute.rs
  crates/metal-proc-macros/src/spans/derive.rs
Labels: pr: bugfix, a: errors

#14 refactor(metal-lexer): Use Rust 2024 range types.
  crates/metal-lexer/src/lib.rs
  crates/metal-lexer/src/span.rs
Labels: pr: improvement

#12 docs: improve readme
  README.md
Labels: comp: easy, p: low, pr: improvement, a: docs

#9 feat(metal-lexer): Implement `metal-lexer`.
  Cargo.toml
  crates/metal-lexer/Cargo.toml
  crates/metal-lexer/src/callbacks.rs
  crates/metal-lexer/src/error.rs
  crates/metal-lexer/src/lib.rs
  crates/metal-lexer/src/tests.rs
  crates/metal-lexer/src/token.rs
Labels: pr: feature

#8 feat: LLVM Backend
  .github/actions/setup-llvm/action.yml
  .github/workflows/clippy.yml
  .github/workflows/test.yml
  Cargo.toml
  crates/metal-ast/src/expr.rs
  crates/metal-ast/src/lib.rs
  crates/metal-ast/src/ty.rs
  crates/metal-llvm/Cargo.toml
  crates/metal-llvm/src/codegen.rs
  crates/metal-llvm/src/lib.rs
  crates/metal-llvm/src/stdlib_priv.rs
Labels: p: high, pr: feature, a: usability, a: llvm
