Repository metallang/metal, pull requests merged in 2025-03, with the labels that each got.

#105 chore: update llvm ci urls
  .github/actions/setup-llvm/action.yml
Labels: a: ci/cd

#103 feat: add unknown as an intermediate MIR type
  crates/metal-codegen-llvm/src/ty.rs
  crates/metal-mir/src/types/mod.rs
Labels: a: mir

#106 deps: Automated nightly version update.
  .github/workflows/clippy.yml
  .github/workflows/rustfmt.yml
  .github/workflows/shear.yml
  .github/workflows/test.yml
Labels: a: deps

#110 deps: Automated nightly version update.
  .github/workflows/clippy.yml
  .github/workflows/rustfmt.yml
  .github/workflows/shear.yml
  .github/workflows/test.yml
Labels: a: deps

#115 deps: Automated nightly version update.
  .github/workflows/audit.yml
  .github/workflows/clippy.yml
  .github/workflows/license-headers.yml
  .github/workflows/nightlies.yml
  .github/workflows/rustfmt.yml
  .github/workflows/shear.yml
  .github/workflows/test.yml
Labels: a: deps

#152 deps: Automated nightly version update.
  .github/workflows/clippy.yml
  .github/workflows/rustfmt.yml
  .github/workflows/shear.yml
  .github/workflows/test.yml
Labels: a: deps
